config/routes.rb
Knott::Application.routes.draw do
  get "password_resets/new"
  root :to => 'pages#show', :url => '/'

  mount PennStation::Engine, :at => "admin"
  mount PennStationBlog::Engine, :at => "admin/blog"

  get "logout" => "sessions#destroy", :as => "logout"
  get "login"  => "sessions#new",     :as => "login"

  get "password_resets/new"
  resources :password_resets

  resources :sessions
  resources :pages

  PennStation::Engine.routes.draw do
    resources :grants
    resources :grant_categories
    resources :grant_year_managers
    resources :trustees
  end

  post "search" => "search#index"

  match '/trustees' => 'trustees#show', :via => :get
  match '/trustees/:id' => 'trustees#show', :via => :get
  match '*url' => 'pages#show', :via => :get

end

app/models/grant_year_manager.rb
class GrantYearManager < ActiveRecord::Base
  validates :year, presence: true
  validates :show_this_year, inclusion: { :in => [true, false] }

  class << self
    def displayable_years
      where(:show_this_year => true).order('year')
    end

    def latest_displayable
      displayable_years.last
    end
  end
end

app/controllers/penn_station/grant_categories_controller.rb
module PennStation
  class GrantCategoriesController < ApplicationController
    before_action :set_grant_category, only: [:show, :edit, :update, :destroy]

#    track_admin_activity

    def index
      @grant_categories = GrantCategory.all.order(:name)
    end

    def show
    end

    def new
      @grant_category = GrantCategory.new
    end

    def edit
    end

    def create
      @grant_category = GrantCategory.new(grant_category_params)

      if @grant_category.save
        redirect_to @grant_category, notice: "grant_category #{@grant_category.name} was successfully created."
      else
        render action: 'new'
      end
    end

    def update
      if @grant_category.update(grant_category_params)
        redirect_to @grant_category, notice: "Successfully updated #{@grant_category.name}."
      else
        render action: 'edit'
      end
    end

    def destroy
      @grant_category.destroy
      redirect_to grant_categories_url, notice: "grant_category #{@grant_category.name} was successfully deleted."
    end

    private

    def set_grant_category
      @grant_category = GrantCategory.find(params[:id])
    end

    def grant_category_params
      params.require(:grant_category).permit(:name)
    end
  end
end

app/controllers/penn_station/grant_year_managers_controller.rb
module PennStation
  class GrantYearManagersController < ApplicationController
    before_action :set_grant, only: [:show, :edit, :update, :destroy]

#    track_admin_activity

    def index
      @grant_year_managers = GrantYearManager.all.order(:year)
    end

    def show
    end

    def new
      @grant_year_manager = GrantYearManager.new
    end

    def edit
    end

    def create
      @grant_year_manager = GrantYearManager.new(grant_year_manager_params)

      if @grant_year_manager.save
        redirect_to @grant_year_manager, notice: "grant year manager #{@grant_year_manager.year} was successfully created."
      else
        render action: 'new'
      end
    end

    def update
      if @grant_year_manager.update(grant_year_manager_params)
        redirect_to @grant_year_manager, notice: "Successfully updated #{@grant_year_manager.year}."
      else
        render action: 'edit'
      end
    end

    def destroy
      @grant_year_manager.destroy
      redirect_to grant_year_managers_url, notice: "grant #{@grant_year_manager.year} was successfully deleted."
    end

    private

    def set_grant
      @grant_year_manager = GrantYearManager.find(params[:id])
    end

    def grant_year_manager_params
      params.require(:grant_year_manager).permit(:year,:show_this_year)
    end
  end
end

app/controllers/penn_station/grants_controller.rb
module PennStation
  class GrantsController < ApplicationController
    before_action :set_grant, only: [:show, :edit, :update, :destroy]

#    track_admin_activity

    def index
      @grants = Grant.all.order(:recipient)
    end

    def show
    end

    def new
      @grant = Grant.new
    end

    def edit
    end

    def create
      @grant = Grant.new(grant_params)
# g.grant_categories = GrantCategory.where(:id => [1,2,3])
      @grant.feature_on_home_page = params['grant'].has_key?('feature_on_home_page') ? true : false

      if @grant.save
        @grant.grant_categories = GrantCategory.where(:id => params['grant_categories'])
        redirect_to edit_grant_path(@grant), notice: "Grant for #{@grant.recipient} was successfully created."
      else
        render action: 'new'
      end
    end

    def update
      if @grant.update(grant_params)
        @grant.grant_categories = GrantCategory.where(:id => params['grant_categories'])
        redirect_to edit_grant_path(@grant), notice: "Successfully updated grant for #{@grant.recipient}."
      else
        render action: 'edit'
      end
    end

    def destroy
      @grant.grant_categories = []
      @grant.destroy
      redirect_to grants_url, notice: "grant #{@grant.recipient} was successfully deleted."
    end

    private

    def set_grant
      @grant = Grant.find(params[:id])
    end

    def grant_params
      params.require(:grant).permit(:recipient,:description,:value,:year,:featured_on_home_page)
    end
  end
end

app/controllers/penn_station/trustees_controller.rb
module PennStation
  class TrusteesController < ApplicationController
    before_action :set_trustee, only: [:show, :edit, :update, :destroy]

    track_admin_activity

    def index
      @trustees = Trustee.all.order(:name)
    end

    def show
    end

    def new
      @trustee = Trustee.new
    end

    def edit
    end

    def create
      @trustee = Trustee.new(trustee_params)

      if @trustee.save
        redirect_to edit_trustee_path(@trustee), notice: "trustee #{@trustee.name} was successfully created."
      else
        render action: 'new'
      end
    end

    def update
      if @trustee.update(trustee_params)
        redirect_to edit_trustee_path(@trustee), notice: "Successfully updated trustee #{@trustee.name}."
      else
        render action: 'edit'
      end
    end

    def destroy
      @trustee.destroy
      redirect_to trustees_url, notice: "trustee #{@trustee.name} was successfully deleted."
    end

    private

    def set_trustee
      @trustee = Trustee.find(params[:id])
    end

    def trustee_params
      plist = params.require(:trustee).permit(:name, :email, :password, :password_confirmation)
    end
  end
end

app/views/penn_station/grant_year_managers/_form.html.erb
<%= form_for grant_year_manager do |f| %>
  <% if grant_year_manager.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in grant_year_manager.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :year %>
    <%= f.text_field :year %>
  </div>

  <div class="field">
    <%= f.label :show_this_year %>
    <%= f.check_box :show_this_year %>
  </div>

  <div class="actions"><%= f.submit 'Save' %></div>

<% end %>

app/views/penn_station/grant_year_managers/edit.html.erb
<% content_for :toolbar_links do %>
  <li><%= link_to "Back to all grants", grants_path, class: "button delete_button" %></li>
  <li><%= link_to "Back to all displayable grants by year", grant_year_managers_path %></li>
  <li><%= link_to "Delete this grant_year_manager", @grant_year_manager, method: :delete, data: { confirm: 'Are you sure?' }, class: "button delete_button" %></li>
<% end %>

<h1>Edit grant year manager for <%= @grant_year_manager.year %></h1>
<%= render(:partial => "penn_station/grant_year_managers/form", :locals => {:grant_year_manager => @grant_year_manager}) %>

app/views/penn_station/grant_year_managers/index.html.erb
<% content_for :toolbar_links do %>
  <li><%= link_to "Back to all grants", grants_path, class: "button delete_button" %></li>
  <li><%= link_to "Add a new grant year manager", new_grant_year_manager_path %></li>
<% end %>

<h1>Manage grant year managers</h1>

<ol id="<%= controller.controller_name %>_index" class="index">
  <li class="title-row row">
    <ol class="">
      <li class="year">Year</li>
			<li class="show_this_year">Show this year</li>
    </ol>
  </li>

  <% @grant_year_managers.each do |grant_year_manager| %>
    <li id="<%= grant_year_manager.id %>" class="row  <%= cycle("even", "odd") -%>">
      <ol class="cols">
      <li class="year"><a href="<%= edit_grant_year_manager_path(grant_year_manager) %>"><%= grant_year_manager.year %> <%= image_tag("edit.png") %></a></li>
      <li class="show_this_year"><%= grant_year_manager.show_this_year ? 'Y' : 'N' %></li>
      </ol>
    </li>
  <% end %>
</ol>

app/views/penn_station/grant_year_managers/new.html.erb
<% content_for :toolbar_links do %>
  <li><%= link_to "Back to all grants", grants_path, class: "button delete_button" %></li>
  <li><%= link_to "Back to all displayable grants by year", grant_year_managers_path %></li>
<% end %>

<h1>Create a new grant year manager</h1>
<%= render(:partial => "penn_station/grant_year_managers/form", :locals => {:grant_year_manager => @grant_year_manager}) %>

app/views/penn_station/grant_year_managers/show.html.erb
<% content_for :toolbar_links do %>
  <li><%= link_to "Back to all grants", grants_path, class: "button delete_button" %></li>
  <li><%= link_to "Back to all displayable grants by year", grant_year_managers_path %></li>
  <li><%= link_to "Delete this grant year manager", @grant_year_manager, method: :delete, data: { confirm: 'Are you sure?' }, class: "button delete_button" %></li>
<% end %>

<div id="<%= controller.controller_name %>">
  <h1>Show grant year manager for <%= @grant_year_manager.year %></h1>
  <%= render(:partial => "penn_station/grant_year_managers/form", :locals => {:grant_year_manager=> @grant_year_manager}) %>
</div>