config/routes.rb
Knott::Application.routes.draw do
  get "password_resets/new"
  root :to => 'pages#show', :url => '/'

  mount PennStation::Engine, :at => "admin"
  mount PennStationBlog::Engine, :at => "admin/blog"

  get "logout" => "sessions#destroy", :as => "logout"
  get "login"  => "sessions#new",     :as => "login"

  get "password_resets/new"
  resources :password_resets

  resources :sessions
  resources :pages

  PennStation::Engine.routes.draw do
    resources :grants
    resources :grant_categories
    resources :grant_year_managers
    resources :trustees
  end

  post "search" => "search#index"

  match '/trustees' => 'trustees#show', :via => :get
  match '/trustees/:id' => 'trustees#show', :via => :get
  match '*url' => 'pages#show', :via => :get

end

app/models/trustee.rb
class Trustee < ActiveRecord::Base
  has_secure_password

  validates :email, presence: true,
                    uniqueness: true

  validates :name, :presence => true,
                   :uniqueness => true

  validates :password, :length => { :minimum => 8, :if => :validate_password? },
                       :confirmation => { :if => :validate_password? }

  validates :password_confirmation, :length => { :minimum => 8, :if => :validate_password? },
                                    :confirmation => { :if => :validate_password? }

  before_create { generate_token(:auth_token) }

  def self.url
    trustee_page = PennStation::Page.where(:ptype => 'Trustee').first
    trustee_page ? trustee_page.url : '/trustees'
  end

  def self.page
    PennStation::Page.where(:ptype => 'Trustee').first
  end

  def activity_info
    "trustee #{name}"
  end

  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!
    TrusteeMailer.password_reset(self).deliver
  end

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while Trustee.exists?(column => self[column])
  end

  private

  def validate_password?
    password.present? || password_confirmation.present?
  end
end

app/controllers/penn_station/grant_categories_controller.rb
module PennStation
  class GrantCategoriesController < ApplicationController
    before_action :set_grant_category, only: [:show, :edit, :update, :destroy]

#    track_admin_activity

    def index
      @grant_categories = GrantCategory.all.order(:name)
    end

    def show
    end

    def new
      @grant_category = GrantCategory.new
    end

    def edit
    end

    def create
      @grant_category = GrantCategory.new(grant_category_params)

      if @grant_category.save
        redirect_to @grant_category, notice: "grant_category #{@grant_category.name} was successfully created."
      else
        render action: 'new'
      end
    end

    def update
      if @grant_category.update(grant_category_params)
        redirect_to @grant_category, notice: "Successfully updated #{@grant_category.name}."
      else
        render action: 'edit'
      end
    end

    def destroy
      @grant_category.destroy
      redirect_to grant_categories_url, notice: "grant_category #{@grant_category.name} was successfully deleted."
    end

    private

    def set_grant_category
      @grant_category = GrantCategory.find(params[:id])
    end

    def grant_category_params
      params.require(:grant_category).permit(:name)
    end
  end
end

app/controllers/penn_station/grant_year_managers_controller.rb
module PennStation
  class GrantYearManagersController < ApplicationController
    before_action :set_grant, only: [:show, :edit, :update, :destroy]

#    track_admin_activity

    def index
      @grant_year_managers = GrantYearManager.all.order(:year)
    end

    def show
    end

    def new
      @grant_year_manager = GrantYearManager.new
    end

    def edit
    end

    def create
      @grant_year_manager = GrantYearManager.new(grant_year_manager_params)

      if @grant_year_manager.save
        redirect_to @grant_year_manager, notice: "grant year manager #{@grant_year_manager.year} was successfully created."
      else
        render action: 'new'
      end
    end

    def update
      if @grant_year_manager.update(grant_year_manager_params)
        redirect_to @grant_year_manager, notice: "Successfully updated #{@grant_year_manager.year}."
      else
        render action: 'edit'
      end
    end

    def destroy
      @grant_year_manager.destroy
      redirect_to grant_year_managers_url, notice: "grant #{@grant_year_manager.year} was successfully deleted."
    end

    private

    def set_grant
      @grant_year_manager = GrantYearManager.find(params[:id])
    end

    def grant_year_manager_params
      params.require(:grant_year_manager).permit(:year,:show_this_year)
    end
  end
end

app/controllers/penn_station/grants_controller.rb
module PennStation
  class GrantsController < ApplicationController
    before_action :set_grant, only: [:show, :edit, :update, :destroy]

#    track_admin_activity

    def index
      @grants = Grant.all.order(:recipient)
    end

    def show
    end

    def new
      @grant = Grant.new
    end

    def edit
    end

    def create
      @grant = Grant.new(grant_params)
# g.grant_categories = GrantCategory.where(:id => [1,2,3])
      @grant.feature_on_home_page = params['grant'].has_key?('feature_on_home_page') ? true : false

      if @grant.save
        @grant.grant_categories = GrantCategory.where(:id => params['grant_categories'])
        redirect_to edit_grant_path(@grant), notice: "Grant for #{@grant.recipient} was successfully created."
      else
        render action: 'new'
      end
    end

    def update
      if @grant.update(grant_params)
        @grant.grant_categories = GrantCategory.where(:id => params['grant_categories'])
        redirect_to edit_grant_path(@grant), notice: "Successfully updated grant for #{@grant.recipient}."
      else
        render action: 'edit'
      end
    end

    def destroy
      @grant.grant_categories = []
      @grant.destroy
      redirect_to grants_url, notice: "grant #{@grant.recipient} was successfully deleted."
    end

    private

    def set_grant
      @grant = Grant.find(params[:id])
    end

    def grant_params
      params.require(:grant).permit(:recipient,:description,:value,:year,:featured_on_home_page)
    end
  end
end

app/controllers/penn_station/trustees_controller.rb
module PennStation
  class TrusteesController < ApplicationController
    before_action :set_trustee, only: [:show, :edit, :update, :destroy]

    track_admin_activity

    def index
      @trustees = Trustee.all.order(:name)
    end

    def show
    end

    def new
      @trustee = Trustee.new
    end

    def edit
    end

    def create
      @trustee = Trustee.new(trustee_params)

      if @trustee.save
        redirect_to edit_trustee_path(@trustee), notice: "trustee #{@trustee.name} was successfully created."
      else
        render action: 'new'
      end
    end

    def update
      if @trustee.update(trustee_params)
        redirect_to edit_trustee_path(@trustee), notice: "Successfully updated trustee #{@trustee.name}."
      else
        render action: 'edit'
      end
    end

    def destroy
      @trustee.destroy
      redirect_to trustees_url, notice: "trustee #{@trustee.name} was successfully deleted."
    end

    private

    def set_trustee
      @trustee = Trustee.find(params[:id])
    end

    def trustee_params
      plist = params.require(:trustee).permit(:name, :email, :password, :password_confirmation)
    end
  end
end

app/controllers/trustees_controller.rb
class TrusteesController < ApplicationController
  before_filter :authenticate_trustee
  before_filter :current_admin
  before_filter :current_trustee
  helper ::PennStation::EventsHelper

  def show
    if params[:id].nil?
      page = Trustee.page
    else
      page = PennStation::Page.where(url: "/trustees/#{params[:id]}").first
    end

    if page.present?
      @page = page
    else
      render :layout => 'missing_page', :template => 'shared/missing_page'
    end
  end

  private

  def authenticate_trustee
    unless (cookies[:auth_token] and current_trustee) or
           (session[:admin_id] and current_admin)
      redirect_to login_url
    end
  end

end

app/views/penn_station/trustees/_form.html.erb
<%= form_for trustee do |f| %>
  <% if trustee.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in trustee.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="actions"><%= f.submit 'Save' %></div>
<% end %>

app/views/penn_station/trustees/edit.html.erb
<% content_for :toolbar_links do %>
  <li><a href="<%= trustees_path %>">Back to all trustees</a></li>
  <% if current_admin.has_role?("admin") %>
    <li><%= link_to "Delete this trustee", @trustee, method: :delete, data: { confirm: 'Are you sure?' }, class: "button delete_button" %></li>
  <% end %>
<% end %>

<h1>Edit <%= @trustee.name %></h1>
<%= render(:partial => "penn_station/trustees/form", :locals => {:trustee => @trustee}) %>

app/views/penn_station/trustees/index.html.erb
<% content_for :toolbar_links do %>
  <% if current_admin.has_role?("admin") %>
    <li class="trustee"><a href="<%= new_trustee_path %>">Add a new trustee</a></li>
  <% end %>
<% end %>

<h1>Manage site trustee</h1>

<ol id="<%= controller.controller_name %>_index" class="index">
  <li class="title-row row">
    <ol class="">
      <li class="name">Name</li>
      <li class="email">Email</li>
      <li class="updated_at">Last Updated</li>
    </ol>
  </li>

  <% @trustees.each do |trustee| %>
    <li id="<%= trustee.id %>" class="row <%= cycle("even", "odd") -%>">
      <ol class="cols">
        <li class="name">
            <a href="<%= edit_trustee_path(trustee) %>"><%= trustee.name %>
              <%= image_tag("edit.png", class: "normal") %>
              <%= image_tag("edit_over.png", class: "hover") %>
            </a>
          </li>
        <li class="email"><%= trustee.email %></li>
        <li class="updated_at"><%= trustee.updated_at.to_s %><%#= formatted_date_and_time(page.updated_at).humanize %></li>
      </ol>
    </li>
  <% end %>
</ol>

app/views/penn_station/trustees/new.html.erb
<% content_for :toolbar_links do %>
  <li><a href="<%= trustees_path %>">Back to all trustees</a></li>
<% end %>

<h1>Create a new trustee</h1>
<%= render(:partial => "penn_station/trustees/form", :locals => {:trustee => @trustee}) %>

app/views/penn_station/trustees/show.html.erb
<% content_for :toolbar_links do %>
  <li><a href="<%= trustees_path %>">Back to all trustees</a></li>
  <% if current_admin.has_role?("admin") %>
    <li><%= link_to "Delete this trustee", @trustee, method: :delete, data: { confirm: 'Are you sure?' }, class: "button delete_button" %></li>
  <% end %>
<% end %>

<div id="<%= controller.controller_name %>">
  <% if current_admin.has_role?("admin","pennstation_admin") %>
    <h1>Manage <%= @trustee.name %></h1>
    <%= render(:partial => "penn_station/trustees/form", :locals => {:trustee => @trustee}) %>
  <% else %>
    <h1>Show <%= @trustee.name %></h1>
    <%= render(:partial => "penn_station/trustees/form", :locals => {:trustee => @trustee}) %>
  <% end %>
</div>