config/routes.rb
Knott::Application.routes.draw do
  get "password_resets/new"
  root :to => 'pages#show', :url => '/'

  mount PennStation::Engine, :at => "admin"
  mount PennStationBlog::Engine, :at => "admin/blog"

  get "logout" => "sessions#destroy", :as => "logout"
  get "login"  => "sessions#new",     :as => "login"

  get "password_resets/new"
  resources :password_resets

  resources :sessions
  resources :pages

  PennStation::Engine.routes.draw do
    resources :grants
    resources :grant_categories
    resources :grant_year_managers
    resources :trustees
  end

  post "search" => "search#index"

  match '/trustees' => 'trustees#show', :via => :get
  match '/trustees/:id' => 'trustees#show', :via => :get
  match '*url' => 'pages#show', :via => :get

end

app/models/grant_category.rb
class GrantCategory < ActiveRecord::Base
  validates :name, presence: true

  has_many :grant_categorizations, :dependent => :destroy
  has_many :grants, :through => :grant_categorizations

  before_save :create_slug

  class << self
    def protected_ids
      {:discretionary => 9}
    end

    def all_category_slugs
      all.select(:slug).group_by(:slug).map &:slug
    end

    def displayable
      all.reject {|gc| GrantCategory.protected_ids.has_value?(gc.id) }
    end
  end

  def create_slug
    self.slug = name.downcase.gsub(/[ \/]/, "-").gsub(/[^a-z \-]/, "")
  end

  def percentage_of_last_5_years
    g_total = Grant.total_for_last_5_years
    @percentage_of_latest_displayable_year ||= g_total == 0 ? 0 : (total_for_last_5_years.to_f / g_total.to_f) * 100
  end

  def total_for_last_5_years
    grants.select{|g| g.year >= Time.now.year-4 && g.year <= Time.now.year}.inject(0){ |sum, g| sum + g.value }
  end

  def total_for_latest_displayable_year
    grants.select{ |g| g.year == GrantYearManager.latest_displayable.year }.inject(0){ |sum, g| sum + g.value }
  end
end

app/controllers/penn_station/grant_categories_controller.rb
module PennStation
  class GrantCategoriesController < ApplicationController
    before_action :set_grant_category, only: [:show, :edit, :update, :destroy]

#    track_admin_activity

    def index
      @grant_categories = GrantCategory.all.order(:name)
    end

    def show
    end

    def new
      @grant_category = GrantCategory.new
    end

    def edit
    end

    def create
      @grant_category = GrantCategory.new(grant_category_params)

      if @grant_category.save
        redirect_to @grant_category, notice: "grant_category #{@grant_category.name} was successfully created."
      else
        render action: 'new'
      end
    end

    def update
      if @grant_category.update(grant_category_params)
        redirect_to @grant_category, notice: "Successfully updated #{@grant_category.name}."
      else
        render action: 'edit'
      end
    end

    def destroy
      @grant_category.destroy
      redirect_to grant_categories_url, notice: "grant_category #{@grant_category.name} was successfully deleted."
    end

    private

    def set_grant_category
      @grant_category = GrantCategory.find(params[:id])
    end

    def grant_category_params
      params.require(:grant_category).permit(:name)
    end
  end
end

app/controllers/penn_station/grant_year_managers_controller.rb
module PennStation
  class GrantYearManagersController < ApplicationController
    before_action :set_grant, only: [:show, :edit, :update, :destroy]

#    track_admin_activity

    def index
      @grant_year_managers = GrantYearManager.all.order(:year)
    end

    def show
    end

    def new
      @grant_year_manager = GrantYearManager.new
    end

    def edit
    end

    def create
      @grant_year_manager = GrantYearManager.new(grant_year_manager_params)

      if @grant_year_manager.save
        redirect_to @grant_year_manager, notice: "grant year manager #{@grant_year_manager.year} was successfully created."
      else
        render action: 'new'
      end
    end

    def update
      if @grant_year_manager.update(grant_year_manager_params)
        redirect_to @grant_year_manager, notice: "Successfully updated #{@grant_year_manager.year}."
      else
        render action: 'edit'
      end
    end

    def destroy
      @grant_year_manager.destroy
      redirect_to grant_year_managers_url, notice: "grant #{@grant_year_manager.year} was successfully deleted."
    end

    private

    def set_grant
      @grant_year_manager = GrantYearManager.find(params[:id])
    end

    def grant_year_manager_params
      params.require(:grant_year_manager).permit(:year,:show_this_year)
    end
  end
end

app/controllers/penn_station/grants_controller.rb
module PennStation
  class GrantsController < ApplicationController
    before_action :set_grant, only: [:show, :edit, :update, :destroy]

#    track_admin_activity

    def index
      @grants = Grant.all.order(:recipient)
    end

    def show
    end

    def new
      @grant = Grant.new
    end

    def edit
    end

    def create
      @grant = Grant.new(grant_params)
# g.grant_categories = GrantCategory.where(:id => [1,2,3])
      @grant.feature_on_home_page = params['grant'].has_key?('feature_on_home_page') ? true : false

      if @grant.save
        @grant.grant_categories = GrantCategory.where(:id => params['grant_categories'])
        redirect_to edit_grant_path(@grant), notice: "Grant for #{@grant.recipient} was successfully created."
      else
        render action: 'new'
      end
    end

    def update
      if @grant.update(grant_params)
        @grant.grant_categories = GrantCategory.where(:id => params['grant_categories'])
        redirect_to edit_grant_path(@grant), notice: "Successfully updated grant for #{@grant.recipient}."
      else
        render action: 'edit'
      end
    end

    def destroy
      @grant.grant_categories = []
      @grant.destroy
      redirect_to grants_url, notice: "grant #{@grant.recipient} was successfully deleted."
    end

    private

    def set_grant
      @grant = Grant.find(params[:id])
    end

    def grant_params
      params.require(:grant).permit(:recipient,:description,:value,:year,:featured_on_home_page)
    end
  end
end

app/controllers/penn_station/trustees_controller.rb
module PennStation
  class TrusteesController < ApplicationController
    before_action :set_trustee, only: [:show, :edit, :update, :destroy]

    track_admin_activity

    def index
      @trustees = Trustee.all.order(:name)
    end

    def show
    end

    def new
      @trustee = Trustee.new
    end

    def edit
    end

    def create
      @trustee = Trustee.new(trustee_params)

      if @trustee.save
        redirect_to edit_trustee_path(@trustee), notice: "trustee #{@trustee.name} was successfully created."
      else
        render action: 'new'
      end
    end

    def update
      if @trustee.update(trustee_params)
        redirect_to edit_trustee_path(@trustee), notice: "Successfully updated trustee #{@trustee.name}."
      else
        render action: 'edit'
      end
    end

    def destroy
      @trustee.destroy
      redirect_to trustees_url, notice: "trustee #{@trustee.name} was successfully deleted."
    end

    private

    def set_trustee
      @trustee = Trustee.find(params[:id])
    end

    def trustee_params
      plist = params.require(:trustee).permit(:name, :email, :password, :password_confirmation)
    end
  end
end

app/views/penn_station/grant_categories/_form.html.erb
<%= form_for grant_category do |f| %>

  <% if grant_category.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in grant_category.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions"><%= f.submit 'Save' %></div>

<% end %>

app/views/penn_station/grant_categories/edit.html.erb
<% content_for :toolbar_links do %>
  <li><%= link_to "Back to all grants", grants_path, class: "button delete_button" %></li>
  <li><%= link_to "Back to all grant categories", grant_categories_path %></li>
  <li><%= link_to "Delete this grant category", @grant_category, method: :delete, data: { confirm: 'Are you sure?' }, class: "button delete_button" %></li>
<% end %>

<h1>Edit <%= @grant_category.name %></h1>
<%= render(:partial => "penn_station/grant_categories/form", :locals => {:grant_category => @grant_category}) %>

app/views/penn_station/grant_categories/index.html.erb
<% content_for :toolbar_links do %>
  <li><%= link_to "Back to all grants", grants_path, class: "button delete_button" %></li>
  <li><%= link_to "Add a new grant category", new_grant_category_path %></li>
<% end %>

<h1>Manage grant categories</h1>

<ol id="<%= controller.controller_name %>_index" class="index">
  <li class="title-row row">
    <ol class="">
      <li class="name">Name</li>
    </ol>
  </li>

  <% @grant_categories.each do |grant_category| %>
    <li id="<%= grant_category.id %>" class="row  <%= cycle("even", "odd") -%>">
      <ol class="cols">
        <li class="name"><a href="<%= edit_grant_category_path(grant_category) %>"><%= grant_category.name %> <%= image_tag("edit.png") %></a></li>
      </ol>
    </li>
  <% end %>
</ol>

app/views/penn_station/grant_categories/new.html.erb
<% content_for :toolbar_links do %>
  <li><%= link_to "Back to all grants", grants_path, class: "button delete_button" %></li>
  <li><%= link_to "Back to all grant categories", grant_categories_path %></li>
<% end %>

<h1>Create a new grant category</h1>
<%= render(:partial => "penn_station/grant_categories/form", :locals => {:grant_category => @grant_category}) %>

app/views/penn_station/grant_categories/show.html.erb
<% content_for :toolbar_links do %>
  <li><%= link_to "Back to all grants", grants_path, class: "button delete_button" %></li>
  <li><%= link_to "Back to all grant categories", grant_categories_path %></li>
  <li><%= link_to "Delete this grant_category", @grant_category, method: :delete, data: { confirm: 'Are you sure?' }, class: "button delete_button" %></li>
<% end %>

<h1>Show <%= @grant_category.name %></h1>
<%= render(:partial => "penn_station/grant_categories/form", :locals => {:grant_category => @grant_category}) %>