config/routes.rb
Knott::Application.routes.draw do
  get "password_resets/new"
  root :to => 'pages#show', :url => '/'

  mount PennStation::Engine, :at => "admin"
  mount PennStationBlog::Engine, :at => "admin/blog"

  get "logout" => "sessions#destroy", :as => "logout"
  get "login"  => "sessions#new",     :as => "login"

  get "password_resets/new"
  resources :password_resets

  resources :sessions
  resources :pages

  PennStation::Engine.routes.draw do
    resources :grants
    resources :grant_categories
    resources :grant_year_managers
    resources :trustees
  end

  post "search" => "search#index"

  match '/trustees' => 'trustees#show', :via => :get
  match '/trustees/:id' => 'trustees#show', :via => :get
  match '*url' => 'pages#show', :via => :get

end

app/models/grant.rb
class Grant < ActiveRecord::Base
  validates :recipient, presence: true
  validates :year, presence: true
  validates :feature_on_home_page, inclusion: { :in => [true, false] }

  has_many :grant_categorizations
  has_many :grant_categories, :through => :grant_categorizations

  class << self
    def for_years(years)
      where(:year => years).order("year DESC, recipient")
    end

    def with_categories(categories)
      includes(:grant_categories).where("grant_categories.name" => categories).order("grant_categories.name")
    end

    def total_for_last_5_years
      this_year = GrantYearManager.latest_displayable.year
      Grant.where('year <= ? and year >= ?',this_year,this_year-4).sum('value')
    end

    def total_for_latest_displayable_year
      Grant.where(:year => GrantYearManager.latest_displayable.year).sum('value')
    end
  end

  def category_names
    grant_categories.map &:name
  end

end

__END__

class Grant < ActiveRecord::Base

  class << self
    def total_for_latest_displayable_year
      Grant.sum(:value, :conditions => ["year = ?", GrantYearManager.latest_displayable_year])
    end
  end

  belongs_to :uploaded_image
  has_many :grant_categorizations, :include => :grant_category, :dependent => :destroy
  has_many :grant_categories, :through => :grant_categorizations

  has_finder :for_years, lambda { |years| {
    :order      => "year DESC, recipient",
    :conditions => { :year => [years].flatten } } }
  has_finder :with_categories, lambda { |categories| {
    :include    => { :grant_categorizations => :grant_category },
    :order      => "grant_category.name",
    :conditions => { "grant_categories.slug" => [categories].flatten } } }
  has_finder :featured, :order => 'year DESC, recipient', :conditions => ["feature_on_home_page = ?", true]

  attr_accessor :grant_category_ids
  after_save :update_grant_category_ids

  after_save :create_new_grant_year_manager

  validates_presence_of :recipient, :year
  validates_presence_of :uploaded_image, :if => :feature_on_home_page

  def category_names
    grant_categories.map &:name
  end

  def value=(new_value)
    write_attribute :value, new_value.gsub(/[^0-9]/,'')
  end

  def feature_on_home_page
    read_attribute :feature_on_home_page || false
  end

  private
    def update_grant_category_ids
      self.grant_categorizations.clear
      if grant_category_ids.nil?
        self.grant_categorizations.create(:grant_category_id => GrantCategory.protected_ids[:discretionary])
      else
        grant_category_ids.each { |gc_id| self.grant_categorizations.create(:grant_category_id => gc_id) unless gc_id.blank? }
      end
      reload
      self.grant_category_ids = nil
    end

    def create_new_grant_year_manager
      year = self.year
      GrantYearManager.create(:year => year, :show_this_year => false) unless GrantYearManager.exists?(:year => year)
    end
end

app/controllers/penn_station/grant_categories_controller.rb
module PennStation
  class GrantCategoriesController < ApplicationController
    before_action :set_grant_category, only: [:show, :edit, :update, :destroy]

#    track_admin_activity

    def index
      @grant_categories = GrantCategory.all.order(:name)
    end

    def show
    end

    def new
      @grant_category = GrantCategory.new
    end

    def edit
    end

    def create
      @grant_category = GrantCategory.new(grant_category_params)

      if @grant_category.save
        redirect_to @grant_category, notice: "grant_category #{@grant_category.name} was successfully created."
      else
        render action: 'new'
      end
    end

    def update
      if @grant_category.update(grant_category_params)
        redirect_to @grant_category, notice: "Successfully updated #{@grant_category.name}."
      else
        render action: 'edit'
      end
    end

    def destroy
      @grant_category.destroy
      redirect_to grant_categories_url, notice: "grant_category #{@grant_category.name} was successfully deleted."
    end

    private

    def set_grant_category
      @grant_category = GrantCategory.find(params[:id])
    end

    def grant_category_params
      params.require(:grant_category).permit(:name)
    end
  end
end

app/controllers/penn_station/grant_year_managers_controller.rb
module PennStation
  class GrantYearManagersController < ApplicationController
    before_action :set_grant, only: [:show, :edit, :update, :destroy]

#    track_admin_activity

    def index
      @grant_year_managers = GrantYearManager.all.order(:year)
    end

    def show
    end

    def new
      @grant_year_manager = GrantYearManager.new
    end

    def edit
    end

    def create
      @grant_year_manager = GrantYearManager.new(grant_year_manager_params)

      if @grant_year_manager.save
        redirect_to @grant_year_manager, notice: "grant year manager #{@grant_year_manager.year} was successfully created."
      else
        render action: 'new'
      end
    end

    def update
      if @grant_year_manager.update(grant_year_manager_params)
        redirect_to @grant_year_manager, notice: "Successfully updated #{@grant_year_manager.year}."
      else
        render action: 'edit'
      end
    end

    def destroy
      @grant_year_manager.destroy
      redirect_to grant_year_managers_url, notice: "grant #{@grant_year_manager.year} was successfully deleted."
    end

    private

    def set_grant
      @grant_year_manager = GrantYearManager.find(params[:id])
    end

    def grant_year_manager_params
      params.require(:grant_year_manager).permit(:year,:show_this_year)
    end
  end
end

app/controllers/penn_station/grants_controller.rb
module PennStation
  class GrantsController < ApplicationController
    before_action :set_grant, only: [:show, :edit, :update, :destroy]

#    track_admin_activity

    def index
      @grants = Grant.all.order(:recipient)
    end

    def show
    end

    def new
      @grant = Grant.new
    end

    def edit
    end

    def create
      @grant = Grant.new(grant_params)
# g.grant_categories = GrantCategory.where(:id => [1,2,3])
      @grant.feature_on_home_page = params['grant'].has_key?('feature_on_home_page') ? true : false

      if @grant.save
        @grant.grant_categories = GrantCategory.where(:id => params['grant_categories'])
        redirect_to edit_grant_path(@grant), notice: "Grant for #{@grant.recipient} was successfully created."
      else
        render action: 'new'
      end
    end

    def update
      if @grant.update(grant_params)
        @grant.grant_categories = GrantCategory.where(:id => params['grant_categories'])
        redirect_to edit_grant_path(@grant), notice: "Successfully updated grant for #{@grant.recipient}."
      else
        render action: 'edit'
      end
    end

    def destroy
      @grant.grant_categories = []
      @grant.destroy
      redirect_to grants_url, notice: "grant #{@grant.recipient} was successfully deleted."
    end

    private

    def set_grant
      @grant = Grant.find(params[:id])
    end

    def grant_params
      params.require(:grant).permit(:recipient,:description,:value,:year,:featured_on_home_page)
    end
  end
end

app/controllers/penn_station/trustees_controller.rb
module PennStation
  class TrusteesController < ApplicationController
    before_action :set_trustee, only: [:show, :edit, :update, :destroy]

    track_admin_activity

    def index
      @trustees = Trustee.all.order(:name)
    end

    def show
    end

    def new
      @trustee = Trustee.new
    end

    def edit
    end

    def create
      @trustee = Trustee.new(trustee_params)

      if @trustee.save
        redirect_to edit_trustee_path(@trustee), notice: "trustee #{@trustee.name} was successfully created."
      else
        render action: 'new'
      end
    end

    def update
      if @trustee.update(trustee_params)
        redirect_to edit_trustee_path(@trustee), notice: "Successfully updated trustee #{@trustee.name}."
      else
        render action: 'edit'
      end
    end

    def destroy
      @trustee.destroy
      redirect_to trustees_url, notice: "trustee #{@trustee.name} was successfully deleted."
    end

    private

    def set_trustee
      @trustee = Trustee.find(params[:id])
    end

    def trustee_params
      plist = params.require(:trustee).permit(:name, :email, :password, :password_confirmation)
    end
  end
end

app/helpers/grants_helper.rb
module GrantsHelper
end

app/views/penn_station/grants/_form.html.erb
<%= form_for grant do |f| %>
  <% if grant.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in grant.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :recipient %>
    <%= f.text_field :recipient %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :value %>
    <%= f.text_field :value %>
  </div>

  <div class="field">
    <%= f.label :year %>
    <%= f.text_field :year %>
  </div>

  <div class="field">
    <label>Grant Categories</label>
    <div class="grants">
      <ol>
        <% GrantCategory.all.order('name').each do |category| %>
          <li>
            <input type="radio" id="grant_category_<%= category.id %>" name="grant_categories[]" value="<%= category.id %>" <%= grant.grant_categories.map(&:id).include?(category.id) ? "checked" : "" %>/>
            <label for="grant_category_<%= category.id %>"> <%= category.name %></label>
          </li>
        <% end %>
      </ol>
    </div>
  </div>

  <%= f.hidden_field :feature_on_home_page, value: false %>

  <div class="actions"><%= f.submit 'Save' %></div>

<% end %>

app/views/penn_station/grants/edit.html.erb
<% content_for :toolbar_links do %>
  <li><%= link_to "Back to all grants", grants_path, class: "button delete_button" %></li>
  <li><%= link_to "Delete this grant", @grant, method: :delete, data: { confirm: 'Are you sure?' }, class: "button delete_button" %></li>
<% end %>

<h1>Edit <%= @grant.recipient %></h1>
<%= render(:partial => "penn_station/grants/form", :locals => {:grant => @grant}) %>

app/views/penn_station/grants/index.html.erb
<% content_for :toolbar_links do %>
  <li><%= link_to "Add a new grant", new_grant_path %></li>
  <li><%= link_to "Manage grant categories", grant_categories_path %></li>
  <li><%= link_to "Manage displayable grants by year", grant_year_managers_path %></li>
<% end %>

<h1>Manage grants</h1>

<ol id="<%= controller.controller_name %>_index" class="index">
  <li class="title-row row">
    <ol class="">
      <li class="name">Name</li>
      <li class="value">Value</li>
      <li class="year">Year</li>
      <li class="category">Category</li>
    </ol>
  </li>

  <% @grants.each do |grant| %>
    <li id="<%= grant.id %>" class="row  <%= cycle("even", "odd") -%>">
      <ol class="cols">
        <li class="name">
            <a href="<%= edit_grant_path(grant) %>"><%= grant.recipient %>
              <%= image_tag("edit.png", class: "normal") %>
              <%= image_tag("edit_over.png", class: "hover") %>
            </a>
          </li>
        <li class="value"><%= number_to_currency grant.value, :precision => 0 %></li>
        <li class="year"><%= grant.year %></li>
        <li class="categories"><span class="categories"><%= grant.category_names.join ', ' %></span></li>
      </ol>
    </li>
  <% end %>
</ol>

app/views/penn_station/grants/new.html.erb
<% content_for :toolbar_links do %>
  <li><%= link_to "Back to all grants", grants_path, class: "button delete_button" %></li>
<% end %>

<h1>Create a new grant</h1>
<%= render(:partial => "penn_station/grants/form", :locals => {:grant => @grant}) %>

app/views/penn_station/grants/show.html.erb
<% content_for :toolbar_links do %>
  <li><%= link_to "Back to all grants", grants_path, class: "button delete_button" %></li>
  <li><%= link_to "Delete this grant", @grant, method: :delete, data: { confirm: 'Are you sure?' }, class: "button delete_button" %></li>
<% end %>

<h1>Show <%= @grant.recipient %></h1>
<%= render(:partial => "penn_station/grants/form", :locals => {:grant=> @grant}) %>